library(tidyverse)
library(ontologyIndex)

cl <- ontoProc::getCellOnto()
celltype_conversion_long <- read_tsv("Data/celltype_conversion_with_ontology.txt") %>%
  rowwise() %>%
  mutate(all_labels = str_split(all_labels, ";")) %>%
  unnest(cols = c(all_labels))


# Load Mahmoud's reference
sref <- readRDS("/bigdata/mahmoudy/humanCellTypeAtlas.rds")

# Make tibble
sref.tbl <- tibble(ont.main = NA, label.main = NA, ont.fine = sref$cl.id, label.fine = sref$lowest.label,
       sample = as.character(sref$samples), dataset = as.character(sref$series), info = sref$tissue_titles)

# Remove progenitor cell types
sref.tbl <- sref.tbl[!sref.tbl$label.fine %in%
                       unique(sref.tbl$label.fine[grepl("progenitor", sref.tbl$label.fine, ignore.case = TRUE)]),]

# Remove those cell types
sref.tbl <- sref.tbl[!sref.tbl$label.fine %in%
                     c("peripheral blood mononuclear cell", "blood cell", "plasma cell", "stromal cell", "kidney cell", "neural cell", "mononuclear cell",
                       "interneuron", "hematopoietic cell", "myeloid cell", "urothelial cell"),]

sref.tbl[sref.tbl$label.fine == "corneal endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "corneal endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "fibroblast",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "fibroblast",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "foreskin fibroblast",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "foreskin fibroblast",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "hepatocyte",]$ont.main <- "CL:0000182"
sref.tbl[sref.tbl$label.fine == "hepatocyte",]$label.main <- "hepatocyte"
sref.tbl[sref.tbl$label.fine == "endothelial cell of hepatic sinusoid",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "endothelial cell of hepatic sinusoid",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "smooth muscle cell",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "smooth muscle cell",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "bronchial epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "bronchial epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "embryonic stem cell",]$ont.main <- "CL:0000034"
sref.tbl[sref.tbl$label.fine == "embryonic stem cell",]$label.main <- "stem cell"
sref.tbl[sref.tbl$label.fine == "pancreatic A cell",]$ont.main <- "CL:0000171"
sref.tbl[sref.tbl$label.fine == "pancreatic A cell",]$label.main <- "pancreatic A cell"
sref.tbl[sref.tbl$label.fine == "type B pancreatic cell",]$ont.main <- "CL:0000169"
sref.tbl[sref.tbl$label.fine == "type B pancreatic cell",]$label.main <- "type B pancreatic cell"
sref.tbl[sref.tbl$label.fine == "endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "microvascular endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "microvascular endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "T cell",]$ont.main <- "CL:0000084"
sref.tbl[sref.tbl$label.fine == "T cell",]$label.main <- "T cell"
sref.tbl[sref.tbl$label.fine == "B cell",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "B cell",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "germinal center B cell",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "germinal center B cell",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "granulosa cell",]$ont.main <- "CL:0000501"
sref.tbl[sref.tbl$label.fine == "granulosa cell",]$label.main <- "granulosa cell"
sref.tbl[sref.tbl$label.fine == "neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "mammary gland epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "mammary gland epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "neuron of cerebral cortex",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "neuron of cerebral cortex",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "lymphocyte",]$ont.main <- "CL:0000542"
sref.tbl[sref.tbl$label.fine == "lymphocyte",]$label.main <- "lymphocyte"
sref.tbl[sref.tbl$label.fine == "keratinocyte",]$ont.main <- "CL:0000362"
sref.tbl[sref.tbl$label.fine == "keratinocyte",]$label.main <- "epidermal cell"
sref.tbl[sref.tbl$label.fine == "muscle cell",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "muscle cell",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "granulocyte",]$ont.main <- "CL:0000094"
sref.tbl[sref.tbl$label.fine == "granulocyte",]$label.main <- "granulocyte"
sref.tbl[sref.tbl$label.fine == "monocyte",]$ont.main <- "CL:0000576"
sref.tbl[sref.tbl$label.fine == "monocyte",]$label.main <- "monocyte"
sref.tbl[sref.tbl$label.fine == "motor neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "motor neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "CD4-positive, alpha-beta T cell",]$ont.main <- "CL:0000624"
sref.tbl[sref.tbl$label.fine == "CD4-positive, alpha-beta T cell",]$label.main <- "CD4-positive, alpha-beta T cell"
sref.tbl[sref.tbl$label.fine == "naive thymus-derived CD4-positive, alpha-beta T cell",]$ont.main <- "CL:0000624"
sref.tbl[sref.tbl$label.fine == "naive thymus-derived CD4-positive, alpha-beta T cell",]$label.main <- "CD4-positive, alpha-beta T cell"
sref.tbl[sref.tbl$label.fine == "mesenchymal stem cell",]$ont.main <- "CL:0000034"
sref.tbl[sref.tbl$label.fine == "mesenchymal stem cell",]$label.main <- "stem cell"
sref.tbl[sref.tbl$label.fine == "dopaminergic neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "dopaminergic neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "cardiac muscle cell",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "cardiac muscle cell",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "Merkel cell",]$ont.main <- "CL:0000362"
sref.tbl[sref.tbl$label.fine == "Merkel cell",]$label.main <- "epidermal cell"
sref.tbl[sref.tbl$label.fine == "endodermal cell",]$ont.main <- "CL:0000223"
sref.tbl[sref.tbl$label.fine == "endodermal cell",]$label.main <- "endodermal cell"
sref.tbl[sref.tbl$label.fine == "erythroblast",]$ont.main <- "CL:0000765"
sref.tbl[sref.tbl$label.fine == "erythroblast",]$label.main <- "erythroblast"
sref.tbl[sref.tbl$label.fine == "naive T cell",]$ont.main <- "CL:0000084"
sref.tbl[sref.tbl$label.fine == "naive T cell",]$label.main <- "T cell"
sref.tbl[sref.tbl$label.fine == "macrophage",]$ont.main <- "CL:0000235"
sref.tbl[sref.tbl$label.fine == "macrophage",]$label.main <- "macrophage"
sref.tbl[sref.tbl$label.fine == "osteoblast",]$ont.main <- "CL:0000062"
sref.tbl[sref.tbl$label.fine == "osteoblast",]$label.main <- "osteoblast"
sref.tbl[sref.tbl$label.fine == "respiratory epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "respiratory epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "skin fibroblast",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "skin fibroblast",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "white fat cell",]$ont.main <- "CL:0000136"
sref.tbl[sref.tbl$label.fine == "white fat cell",]$label.main <- "fat cell"
sref.tbl[sref.tbl$label.fine == "brown fat cell",]$ont.main <- "CL:0000136"
sref.tbl[sref.tbl$label.fine == "brown fat cell",]$label.main <- "fat cell"
sref.tbl[sref.tbl$label.fine == "myotube",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "myotube",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "T follicular helper cell",]$ont.main <- "CL:0000084"
sref.tbl[sref.tbl$label.fine == "T follicular helper cell",]$label.main <- "T cell"
sref.tbl[sref.tbl$label.fine == "effector T cell",]$ont.main <- "CL:0000084"
sref.tbl[sref.tbl$label.fine == "effector T cell",]$label.main <- "T cell"
sref.tbl[sref.tbl$label.fine == "astrocyte",]$ont.main <- "CL:0000125"
sref.tbl[sref.tbl$label.fine == "astrocyte",]$label.main <- "glial cell"
sref.tbl[sref.tbl$label.fine == "proerythroblast",]$ont.main <- "CL:0000547"
sref.tbl[sref.tbl$label.fine == "proerythroblast",]$label.main <- "proerythroblast"
sref.tbl[sref.tbl$label.fine == "dendritic cell",]$ont.main <- "CL:0000451"
sref.tbl[sref.tbl$label.fine == "dendritic cell",]$label.main <- "dendritic cell"
sref.tbl[sref.tbl$label.fine == "neutrophil",]$ont.main <- "CL:0000775"
sref.tbl[sref.tbl$label.fine == "neutrophil",]$label.main <- "neutrophil"
sref.tbl[sref.tbl$label.fine == "fat cell",]$ont.main <- "CL:0000136"
sref.tbl[sref.tbl$label.fine == "fat cell",]$label.main <- "fat cell"
sref.tbl[sref.tbl$label.fine == "peripheral sensory neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "peripheral sensory neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "B cell, CD19-positive",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "B cell, CD19-positive",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "memory T cell",]$ont.main <- "CL:0000084"
sref.tbl[sref.tbl$label.fine == "memory T cell",]$label.main <- "T cell"
sref.tbl[sref.tbl$label.fine == "epithelial cell of prostate",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "epithelial cell of prostate",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "myometrial cell",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "myometrial cell",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "chondrocyte",]$ont.main <- "CL:0000138"
sref.tbl[sref.tbl$label.fine == "chondrocyte",]$label.main <- "chondrocyte"
sref.tbl[sref.tbl$label.fine == "neuron of the forebrain",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "neuron of the forebrain",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "mesothelial cell",]$ont.main <- "CL:0000077"
sref.tbl[sref.tbl$label.fine == "mesothelial cell",]$label.main <- "mesothelial cell"
sref.tbl[sref.tbl$label.fine == "cord blood hematopoietic stem cell",]$ont.main <- "CL:0000034"
sref.tbl[sref.tbl$label.fine == "cord blood hematopoietic stem cell",]$label.main <- "stem cell"
sref.tbl[sref.tbl$label.fine == "natural killer cell",]$ont.main <- "CL:0000623"
sref.tbl[sref.tbl$label.fine == "natural killer cell",]$label.main <- "natural killer cell"
sref.tbl[sref.tbl$label.fine == "CD8-positive, alpha-beta T cell",]$ont.main <- "CL:0000625"
sref.tbl[sref.tbl$label.fine == "CD8-positive, alpha-beta T cell",]$label.main <- "CD8-positive, alpha-beta T cell"
sref.tbl[sref.tbl$label.fine == "leukocyte",]$ont.main <- "CL:0000738"
sref.tbl[sref.tbl$label.fine == "leukocyte",]$label.main <- "leukocyte"
sref.tbl[sref.tbl$label.fine == "vascular associated smooth muscle cell",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "vascular associated smooth muscle cell",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "retinal pigment epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "retinal pigment epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "Kupffer cell",]$ont.main <- "CL:0000235"
sref.tbl[sref.tbl$label.fine == "Kupffer cell",]$label.main <- "macrophage"
sref.tbl[sref.tbl$label.fine == "hematopoietic stem cell",]$ont.main <- "CL:0000034"
sref.tbl[sref.tbl$label.fine == "hematopoietic stem cell",]$label.main <- "stem cell"
sref.tbl[sref.tbl$label.fine == "mature neutrophil",]$ont.main <- "CL:0000775"
sref.tbl[sref.tbl$label.fine == "mature neutrophil",]$label.main <- "neutrophil"
sref.tbl[sref.tbl$label.fine == "plasmacytoid dendritic cell",]$ont.main <- "CL:0000451"
sref.tbl[sref.tbl$label.fine == "plasmacytoid dendritic cell",]$label.main <- "dendritic cell"
sref.tbl[sref.tbl$label.fine == "myeloid dendritic cell",]$ont.main <- "CL:0000451"
sref.tbl[sref.tbl$label.fine == "myeloid dendritic cell",]$label.main <- "dendritic cell"
sref.tbl[sref.tbl$label.fine == "oocyte",]$ont.main <- "CL:0000023"
sref.tbl[sref.tbl$label.fine == "oocyte",]$label.main <- "oocyte"
sref.tbl[sref.tbl$label.fine == "oligodendrocyte",]$ont.main <- "CL:0000125"
sref.tbl[sref.tbl$label.fine == "oligodendrocyte",]$label.main <- "glial cell"
sref.tbl[sref.tbl$label.fine == "chondrocyte",]$ont.main <- "CL:0000138"
sref.tbl[sref.tbl$label.fine == "chondrocyte",]$label.main <- "chondrocyte"
sref.tbl[sref.tbl$label.fine == "calvarial osteoblast",]$ont.main <- "CL:0000062"
sref.tbl[sref.tbl$label.fine == "calvarial osteoblast",]$label.main <- "osteoblast"
sref.tbl[sref.tbl$label.fine == "conventional dendritic cell",]$ont.main <- "CL:0000451"
sref.tbl[sref.tbl$label.fine == "conventional dendritic cell",]$label.main <- "dendritic cell"
sref.tbl[sref.tbl$label.fine == "fibroblast of arm",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "fibroblast of arm",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "epithelial cell of umbilical artery",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "epithelial cell of umbilical artery",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "fibroblast of dermis",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "fibroblast of dermis",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "mesangial cell",]$ont.main <- "CL:0000650"
sref.tbl[sref.tbl$label.fine == "mesangial cell",]$label.main <- "mesangial cell"
sref.tbl[sref.tbl$label.fine == "cardiac ventricle fibroblast",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "cardiac ventricle fibroblast",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "bronchus fibroblast of lung",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "bronchus fibroblast of lung",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "endothelial cell of lymphatic vessel",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "endothelial cell of lymphatic vessel",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "decidual natural killer cell, human",]$ont.main <- "CL:0000623"
sref.tbl[sref.tbl$label.fine == "decidual natural killer cell, human",]$label.main <- "natural killer cell"
sref.tbl[sref.tbl$label.fine == "intestinal epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "intestinal epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "epithelial cell of lung",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "epithelial cell of lung",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "glomerular visceral epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "glomerular visceral epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "articular chondrocyte",]$ont.main <- "CL:0000138"
sref.tbl[sref.tbl$label.fine == "articular chondrocyte",]$label.main <- "chondrocyte"
sref.tbl[sref.tbl$label.fine == "pigmented epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "pigmented epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "unswitched memory B cell",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "unswitched memory B cell",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "pulmonary artery endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "pulmonary artery endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "pleural macrophage",]$ont.main <- "CL:0000235"
sref.tbl[sref.tbl$label.fine == "pleural macrophage",]$label.main <- "macrophage"
sref.tbl[sref.tbl$label.fine == "alveolar macrophage",]$ont.main <- "CL:0000235"
sref.tbl[sref.tbl$label.fine == "alveolar macrophage",]$label.main <- "macrophage"
sref.tbl[sref.tbl$label.fine == "trophoblast cell",]$ont.main <- "CL:0000351"
sref.tbl[sref.tbl$label.fine == "trophoblast cell",]$label.main <- "trophoblast cell"
sref.tbl[sref.tbl$label.fine == "endothelial cell of vascular tree",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "endothelial cell of vascular tree",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "epithelial cell of proximal tubule",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "epithelial cell of proximal tubule",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "pericardium fibroblast",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "pericardium fibroblast",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "glomerular endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "glomerular endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "microglial cell",]$ont.main <- "CL:0000129"
sref.tbl[sref.tbl$label.fine == "microglial cell",]$label.main <- "microglial cell"
sref.tbl[sref.tbl$label.fine == "aortic endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "aortic endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "regulatory T cell",]$ont.main <- "CL:0000815"
sref.tbl[sref.tbl$label.fine == "regulatory T cell",]$label.main <- "regulatory T cell"
sref.tbl[sref.tbl$label.fine == "induced T-regulatory cell",]$ont.main <- "CL:0000815"
sref.tbl[sref.tbl$label.fine == "induced T-regulatory cell",]$label.main <- "regulatory T cell"
sref.tbl[sref.tbl$label.fine == "regulatory T cell",]$ont.main <- "CL:0000815"
sref.tbl[sref.tbl$label.fine == "regulatory T cell",]$label.main <- "regulatory T cell"
sref.tbl[sref.tbl$label.fine == "Schwann cell",]$ont.main <- "CL:0000125"
sref.tbl[sref.tbl$label.fine == "Schwann cell",]$label.main <- "glial cell"
sref.tbl[sref.tbl$label.fine == "pericyte cell",]$ont.main <- "CL:0000669"
sref.tbl[sref.tbl$label.fine == "pericyte cell",]$label.main <- "pericyte cell"
sref.tbl[sref.tbl$label.fine == "endocardial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "endocardial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "natural T-regulatory cell",]$ont.main <- "CL:0000815"
sref.tbl[sref.tbl$label.fine == "natural T-regulatory cell",]$label.main <- "regulatory T cell"
sref.tbl[sref.tbl$label.fine == "helper T cell",]$ont.main <- "CL:0000912"
sref.tbl[sref.tbl$label.fine == "helper T cell",]$label.main <- "helper T cell"
sref.tbl[sref.tbl$label.fine == "fibroblast of cardiac tissue",]$ont.main <- "CL:0000057"
sref.tbl[sref.tbl$label.fine == "fibroblast of cardiac tissue",]$label.main <- "fibroblast"
sref.tbl[sref.tbl$label.fine == "brain microvascular endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "brain microvascular endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "spinal cord motor neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "spinal cord motor neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "pigmented ciliary epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "pigmented ciliary epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "myelocyte",]$ont.main <- "CL:0002193"
sref.tbl[sref.tbl$label.fine == "myelocyte",]$label.main <- "myelocyte"
sref.tbl[sref.tbl$label.fine == "promyelocyte",]$ont.main <- "CL:0002193"
sref.tbl[sref.tbl$label.fine == "promyelocyte",]$label.main <- "myelocyte"
sref.tbl[sref.tbl$label.fine == "metamyelocyte",]$ont.main <- "CL:0002193"
sref.tbl[sref.tbl$label.fine == "metamyelocyte",]$label.main <- "myelocyte"
sref.tbl[sref.tbl$label.fine == "myoepithelial cell",]$ont.main <- "CL:0000185"
sref.tbl[sref.tbl$label.fine == "myoepithelial cell",]$label.main <- "myoepithelial cell"
sref.tbl[sref.tbl$label.fine == "endothelial cell of artery",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "endothelial cell of artery",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "pancreatic ductal cell",]$ont.main <- "CL:0002079"
sref.tbl[sref.tbl$label.fine == "pancreatic ductal cell",]$label.main <- "pancreatic ductal cell"
sref.tbl[sref.tbl$label.fine == "hepatic stellate cell",]$ont.main <- "CL:0000632"
sref.tbl[sref.tbl$label.fine == "hepatic stellate cell",]$label.main <- "hepatic stellate cell"
sref.tbl[sref.tbl$label.fine == "respiratory basal cell",]$ont.main <- "CL:0002633"
sref.tbl[sref.tbl$label.fine == "respiratory basal cell",]$label.main <- "respiratory basal cell"
sref.tbl[sref.tbl$label.fine == "pancreatic stellate cell",]$ont.main <- "CL:0002410"
sref.tbl[sref.tbl$label.fine == "pancreatic stellate cell",]$label.main <- "pancreatic stellate cell"
sref.tbl[sref.tbl$label.fine == "foreskin keratinocyte",]$ont.main <- "CL:0000362"
sref.tbl[sref.tbl$label.fine == "foreskin keratinocyte",]$label.main <- "epidermal cell"
sref.tbl[sref.tbl$label.fine == "exhausted T cell",]$ont.main <- "CL:0011025"
sref.tbl[sref.tbl$label.fine == "exhausted T cell",]$label.main <- "exhausted T cell"
sref.tbl[sref.tbl$label.fine == "neural crest cell",]$ont.main <- "CL:0011012"
sref.tbl[sref.tbl$label.fine == "neural crest cell",]$label.main <- "neural crest cell"
sref.tbl[sref.tbl$label.fine == "brain pericyte",]$ont.main <- "CL:0000669"
sref.tbl[sref.tbl$label.fine == "brain pericyte",]$label.main <- "pericyte cell"
sref.tbl[sref.tbl$label.fine == "gamma-delta T cell",]$ont.main <- "CL:0000798"
sref.tbl[sref.tbl$label.fine == "gamma-delta T cell",]$label.main <- "gamma-delta T cell"
sref.tbl[sref.tbl$label.fine == "sensory neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "sensory neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "mast cell",]$ont.main <- "CL:0000097"
sref.tbl[sref.tbl$label.fine == "mast cell",]$label.main <- "mast cell"
sref.tbl[sref.tbl$label.fine == "memory B cell",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "memory B cell",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "naive B cell",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "naive B cell",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "GABAergic neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "GABAergic neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "eosinophil",]$ont.main <- "CL:0000771"
sref.tbl[sref.tbl$label.fine == "eosinophil",]$label.main <- "eosinophil"
sref.tbl[sref.tbl$label.fine == "T-helper 1 cell",]$ont.main <- "CL:0000912"
sref.tbl[sref.tbl$label.fine == "T-helper 1 cell",]$label.main <- "helper T cell"
sref.tbl[sref.tbl$label.fine == "Be cell",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "Be cell",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "subcutaneous fat cell",]$ont.main <- "CL:0000136"
sref.tbl[sref.tbl$label.fine == "subcutaneous fat cell",]$label.main <- "fat cell"
sref.tbl[sref.tbl$label.fine == "excitatory neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "excitatory neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "lung endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "lung endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "myeloblast",]$ont.main <- "CL:0000835"
sref.tbl[sref.tbl$label.fine == "myeloblast",]$label.main <- "myeloblast"
sref.tbl[sref.tbl$label.fine == "classical monocyte",]$ont.main <- "CL:0000576"
sref.tbl[sref.tbl$label.fine == "classical monocyte",]$label.main <- "monocyte"
sref.tbl[sref.tbl$label.fine == "adipose microvascular endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "adipose microvascular endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "basophil",]$ont.main <- "CL:0000767"
sref.tbl[sref.tbl$label.fine == "basophil",]$label.main <- "basophil"
sref.tbl[sref.tbl$label.fine == "bladder microvascular endothelial cell",]$ont.main <- "CL:0000115"
sref.tbl[sref.tbl$label.fine == "bladder microvascular endothelial cell",]$label.main <- "endothelial cell"
sref.tbl[sref.tbl$label.fine == "bronchial smooth muscle cell",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "bronchial smooth muscle cell",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "cholangiocyte",]$ont.main <- "CL:1000488"
sref.tbl[sref.tbl$label.fine == "cholangiocyte",]$label.main <- "cholangiocyte"
sref.tbl[sref.tbl$label.fine == "choroid plexus epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "choroid plexus epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "class switched memory B cell",]$ont.main <- "CL:0000236"
sref.tbl[sref.tbl$label.fine == "class switched memory B cell",]$label.main <- "B cell"
sref.tbl[sref.tbl$label.fine == "colon epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "colon epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "corneal epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "corneal epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "preadipocyte",]$ont.main <- "CL:0002334"
sref.tbl[sref.tbl$label.fine == "preadipocyte",]$label.main <- "preadipocyte"
sref.tbl[sref.tbl$label.fine == "T-helper 17 cell",]$ont.main <- "CL:0000912"
sref.tbl[sref.tbl$label.fine == "T-helper 17 cell",]$label.main <- "helper T cell"
sref.tbl[sref.tbl$label.fine == "T-helper 9 cell",]$ont.main <- "CL:0000912"
sref.tbl[sref.tbl$label.fine == "T-helper 9 cell",]$label.main <- "helper T cell"
sref.tbl[sref.tbl$label.fine == "brown preadipocyte",]$ont.main <- "CL:0002334"
sref.tbl[sref.tbl$label.fine == "brown preadipocyte",]$label.main <- "preadipocyte"
sref.tbl[sref.tbl$label.fine == "lens epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "lens epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "cytotoxic T cell",]$ont.main <- "CL:0000910"
sref.tbl[sref.tbl$label.fine == "cytotoxic T cell",]$label.main <- "cytotoxic T cell"
sref.tbl[sref.tbl$label.fine == "synovial cell",]$ont.main <- "CL:0000214"
sref.tbl[sref.tbl$label.fine == "synovial cell",]$label.main <- "synovial cell"
sref.tbl[sref.tbl$label.fine == "aortic smooth muscle cell",]$ont.main <- "CL:0000187"
sref.tbl[sref.tbl$label.fine == "aortic smooth muscle cell",]$label.main <- "muscle cell"
sref.tbl[sref.tbl$label.fine == "megakaryocyte",]$ont.main <- "CL:0000556"
sref.tbl[sref.tbl$label.fine == "megakaryocyte",]$label.main <- "megakaryocyte"
sref.tbl[sref.tbl$label.fine == "iris pigment epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "iris pigment epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "erythrocyte",]$ont.main <- "CL:0000232"
sref.tbl[sref.tbl$label.fine == "erythrocyte",]$label.main <- "erythrocyte"
sref.tbl[sref.tbl$label.fine == "crypt olfactory receptor neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "crypt olfactory receptor neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "duct epithelial cell",]$ont.main <- "CL:0002632"
sref.tbl[sref.tbl$label.fine == "duct epithelial cell",]$label.main <- "epithelial cell"
sref.tbl[sref.tbl$label.fine == "subcutaneous preadipocyte",]$ont.main <- "CL:0002334"
sref.tbl[sref.tbl$label.fine == "subcutaneous preadipocyte",]$label.main <- "preadipocyte"
sref.tbl[sref.tbl$label.fine == "intermediate monocyte",]$ont.main <- "CL:0000576"
sref.tbl[sref.tbl$label.fine == "intermediate monocyte",]$label.main <- "monocyte"
sref.tbl[sref.tbl$label.fine == "club cell",]$ont.main <- "CL:0000158"
sref.tbl[sref.tbl$label.fine == "club cell",]$label.main <- "club cell"
sref.tbl[sref.tbl$label.fine == "Sertoli cell",]$ont.main <- "CL:0000216"
sref.tbl[sref.tbl$label.fine == "Sertoli cell",]$label.main <- "Sertoli cell"
sref.tbl[sref.tbl$label.fine == "glutamatergic neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "glutamatergic neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "midbrain dopaminergic neuron",]$ont.main <- "CL:0000540"
sref.tbl[sref.tbl$label.fine == "midbrain dopaminergic neuron",]$label.main <- "neuron"
sref.tbl[sref.tbl$label.fine == "enterocyte",]$ont.main <- "CL:0000584"
sref.tbl[sref.tbl$label.fine == "enterocyte",]$label.main <- "enterocyte"
sref.tbl[sref.tbl$label.fine == "respiratory basal cell",]$ont.main <- "CL:0000646"
sref.tbl[sref.tbl$label.fine == "respiratory basal cell",]$label.main <- "basal cell"

sref.tbl <- sref.tbl[!is.na(sref.tbl$ont.main),]

sref.df <- as.data.frame(sref.tbl)
sref.data <- as.matrix(sref$data[,sref.df$sample])
all(sref.df$sample == colnames(sref.data))


saveRDS(sref.df, "/bigdata/almogangel/super_ref_for_xcell2/sref_labels.rds")
saveRDS(sref.data, "/bigdata/almogangel/super_ref_for_xcell2/sref_data.rds")

